### ISSUE TITLE
Update router class

### ISSUE THREAD

**Issue by ImMaax** [steampixel/simplePHPPages#1]
Update the [router class](https://github.com/steampixel/simplephprouter/). I'd recommend using Composer.

**Comment by steampixel** [comment]
@ImMaax Yes. This would be the best approach. But at the moment I dont know what the future of this package looks like. I want to think about that a few days. At the moment I want to extract the Component and Portal class and put them into own Git and Composer repos. Than I want to create a repository that shows how to build a little flat file CMS with PHP including this classes using Composer. This repository is also very experimental. I have already a different version that has already some kind of an simple PHP document store. I first want to publish these base classes and than I want to refactor this repo.

**Comment by Hillzacky** [comment]
how to change route 404/405 to another path? thanks.

**Comment by ImMaax** [comment]
Hi! First off, I'd recommend starting a new issue for asking for a solution to your problem. But anyways.

To me, it looks like you just need to call `Route::pathNotFound()` and `Route::methodNotAllowed()` with a callable as the first parameter. Correct me if I'm wrong.

**Comment by Hillzacky** [comment]
OK, should I delete it? sorry i just got on github, and thanks for the time and advice ImMaax

**Comment by steampixel** [comment]
@Hillzacky I have moved your question to this location: https://github.com/steampixel/simplePHPPages/issues/2

**Comment by steampixel** [comment]
Ah^^ Wrong repository^^

**Comment by steampixel** [comment]
@Hillzacky sorry for the confusion^^ I have now moved your issue to the simplePHPRouter repo: https://github.com/steampixel/simplePHPRouter/issues/30
